export const ADD_TO_USER_LOG = 'ADD_TO_USER_LOG';
export const SET_USER_LOG = 'SET_USER_LOG';
export const CLEAR_USER_LOG = 'CLEAR_USER_LOG';
export const NOTE_ERROR = 'NOTE_ERROR';
export const RETRIEVE_USER_LOG_STARTED = 'RETRIEVE_USER_LOG_STARTED';
export const RETRIEVE_USER_LOG_ERROR = 'RETRIEVE_USER_LOG_ERROR';
export const RETRIEVE_USER_LOG_COMPLETED = 'RETRIEVE_USER_LOG_COMPLETED';
export const MEAL_LOADED = 'MEAL_LOADED';
export const MEAL_CLEARED = 'MEAL_CLEARED';
export const DELETE_LOGITEM_STARTED = 'DELETE_LOGITEM_STARTED';
export const DELETE_LOGITEM_DONE = 'DELETE_LOGITEM_DONE';
export const DELETE_LOGITEM_ERROR = 'DELETE_LOGITEM_ERROR';
export const UPDATE_LOGITEM_STARTED = 'UPDATE_LOGITEM_STARTED';
export const UPDATE_LOGITEM_DONE = 'UPDATE_LOGITEM_DONE';
export const UPDATE_LOGITEM_ERROR = 'UPDATE_LOGITEM_ERROR';

