export const POPULAR_FOOD_LOADED = 'POPULAR_FOOD_LOADED';
export const FOODGROUP_LOADED = 'FOODGROUP_LOADED';
export const FOOD_LOADED = 'FOOD_LOADED';
export const FAVORITE_FOOD_LOADED = 'FAVORITE_FOOD_LOADED';
