export const LOGGED_IN_USER = 'LOGGED_IN_USER';
export const LOGIN_LAST_EMAIL = 'LOGIN_LAST_EMAIL';
export const SELECTED_USER_ID = 'SELECTED_USER_ID';
export const SELECTED_USER_NAME = 'SELECTED_USER_NAME';
export const TOKENS = 'TOKENS';
export const BLOOD_SUGAR = 'BLOOD_SUGAR';
export const CARBS = 'CARBS';
export const INVITATION_CODE = 'INVITATION_CODE';
export const TOTALUNITS_INSULIN = 'TOTALUNITS_INSULIN';

export const TOKEN_REFRESH = 'TOKEN_REFRESH';
export const TOKEN_BEARER = 'TOKEN_BEARER';
export const TOKEN_EXPIRATION = 'TOKEN_EXPIRATION';

export const PLATFORM_PUSH_TOKEN = 'PLATFORM_PUSH_TOKEN';
export const NEW_PLATFORM_PUSH_TOKEN = 'NEW_PLATFORM_PUSH_TOKEN';
export const NOTIFICATION_HUB_REGISTRATION = 'NOTIFICATION_HUB_REGISTRATION';
export const IS_PUSH_OFF = 'IS_PUSH_OFF';
export const LATEST_PUSH_SAVE_INFO = 'LATEST_PUSH_SAVE_INFO';

export const SAVED_MEAL_FAVORITES = 'SAVED_MEAL_FAVORITES';
