export const BLOODSUGAR_UPDATE_STARTED = 'BLOODSUGAR_UPDATE_STARTED';
export const BLOODSUGAR_UPDATED = 'BLOODSUGAR_UPDATED';
export const BLOODSUGAR_ERROR = 'BLOODSUGAR_ERROR';
export const BLOODSUGAR_CLEAR = 'BLOODSUGAR_CLEAR';
