export const TOGGLE_PUSH_ON = 'TOGGLE_PUSH_ON';
export const TOGGLE_IS_PUSH_SETUP_COMPLETE = 'TOGGLE_IS_PUSH_SETUP_COMPLETE';
export const FAILED_TO_SET_PUSH_STATE = 'FAILED_TO_SET_PUSH_STATE';
export const NOTIFICATION_OPENED = 'NOTIFICATION_OPENED';
export const NOTIFICATION_RECEIVED = 'NOTIFICATION_RECEIVED';
export const PUSHHANDLE_RECEIVED = 'PUSHHANDLE_RECEIVED';
export const LATEST_PUSH_REG_INFO = 'LATEST_PUSH_REG_INFO';
