export const INITIALIZED = 'INITIALIZED';
export const ROOT_CHANGED = 'ROOT_CHANGED';
export const SET_LOGGEDIN_USER = 'SET_LOGGEDIN_USER';
export const PLATFORM_INFO = 'PLATFORM_INFO';
export const UPDATE_ACCOUNT_NAME = 'UPDATE_ACCOUNT_NAME';
