export const ACCOUNT_CHANGE_STARTED = 'ACCOUNT_CHANGE_STARTED';
export const ACCOUNT_CHANGE_DONE = 'ACCOUNT_CHANGE_DONE';
export const ACCOUNT_CHANGE_ERROR = 'ACCOUNT_CHANGE_ERROR';
export const ACCOUNT_CHANGEPASSWORD_STARTED = 'ACCOUNT_CHANGEPASSWORD_STARTED';
export const ACCOUNT_CHANGEPASSWORD_DONE = 'ACCOUNT_CHANGEPASSWORD_DONE';
export const ACCOUNT_CHANGEPASSWORD_ERROR = 'ACCOUNT_CHANGEPASSWORD_ERROR';
export const ACCOUNT_UPDATE_STARTED = 'ACCOUNT_UPDATE_STARTED';
export const ACCOUNT_UPDATE_DONE = 'ACCOUNT_UPDATE_DONE';
export const ACCOUNT_UPDATE_ERROR = 'ACCOUNT_UPDATE_ERROR';

