export const CARB_ADDED_TO_MEAL = 'CARB_ADDED_TO_MEAL';
export const REMOVE_FOOD_FROM_MEAL = 'REMOVE_FOOD_FROM_MEAL';
export const MEAL_LIST_UPDATED = 'MEAL_LIST_UPDATED';
export const SUBMIT_MEAL = 'SUBMIT_MEAL';
export const CLEAR_TEMP_MEAL_LIST = 'CLEAR_TEMP_MEAL_LIST';
export const UPDATE_MEAL_SAVE_ERROR = 'UPDATE_MEAL_SAVE_ERROR';
export const UPDATE_MEAL_SAVE_STARTED = 'UPDATE_MEAL_SAVE_STARTED';
